### ISSUE TITLE
byte string methods are deprecated and have been removed from njs 0.8.0

### ISSUE THREAD

**Issue by arman-ku** [TuxInvader/nginx-dns#19]
Well, the title pretty much says it all. https://nginx.org/en/docs/njs/changes.html

As expected, nginx.log shows:
`2023/07/15 23:03:33 [error] 20034#20034: *61 js exception: TypeError: (intermediate value)["bytesFrom"] is not a function
    at module (/etc/nginx/njs.d/dns/dns.js:35)`

Any ETA on when the code will be updated? Thanks in advance :)

**Comment by arman-ku** [comment]
Ok, i just looked further into the changes of 0.8.0, and apparently ALL byte string method have been removed, switching to Buffer.
`Since [0.8.0](https://nginx.org/en/docs/njs/changes.html#njs0.8.0), the support for byte strings and byte string methods were removed. When working with byte sequence, the [Buffer](https://nginx.org/en/docs/njs/reference.html#buffer) object and Buffer properties, such as [r.requestBuffer](https://nginx.org/en/docs/njs/reference.html#r_request_buffer), [r.rawVariables](https://nginx.org/en/docs/njs/reference.html#r_raw_variables), should be used.`
https://nginx.org/en/docs/njs/reference.html#string

**Comment by arnaudpn** [comment]
@arman-ku : thanks for reporting this, I already noticed Tony M. here https://www.nginx.com/blog/using-nginx-as-dot-doh-gateway/ before falling on this thread.

44 lines of codes are impacted by obsoleted methods as of version 0.8.0:

> root@XXXBSD:/usr/local/etc/nginx/njs.d # grep -R -E 'bytesFrom|fromBytes|fromUTF8|toBytes|toString|toUTF8' * | wc -l
>       44

I hope @TuxInvader will be able to patch this :-)

**Comment by arnaudpn** [comment]
Hi @TuxInvader ,

Works great ! Thanks for this v2 :-)

I just have an error popping in my logfile at each request:
`2023/07/19 12:12:38 [error] 58066#0: *57804 upstream sent invalid header: "X-DNS-Answers: [HTTPS:\x00..." while reading response header from upstream`
I didn't have this error with the previous versions although code of previous versions also included references to that header.

Thanks again !

**Comment by arman-ku** [comment]
Same for me, works fine, just generates a few new error lines
`2023/07/23 11:23:22 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:26 [error] 112903#112903: *5 upstream sent invalid header: "X-DNS-Answers: [HTTPS:\x00..." while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:28 [error] 112903#112903: *5 upstream sent invalid header: "X-DNS-Answers: [HTTPS:\x00..." while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:28 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:29 [error] 112903#112903: *5 upstream sent invalid header: "X-DNS-Answers: [HTTPS:\x00..." while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:30 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:41 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:46 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:52 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:53 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:57 [error] 112903#112903: *5 upstream sent invalid header: "X-DNS-Answers: [CNAME:youtube-ui.l.google.com],[HTTPS:\x00..." while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:58 [error] 112903#112903: *5 upstream sent invalid header: "X-DNS-Answers: [HTTPS:\x00..." while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:58 [error] 112903#112903: *5 upstream sent invalid header: "X-DNS-Answers: [HTTPS:\x00..." while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:23:59 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:06 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:09 [error] 112903#112903: *5 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:09 [error] 112903#112903: *5 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:12 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:25 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:32 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:37 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:42 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:48 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:52 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:58 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:24:58 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:25:04 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
2023/07/23 11:25:10 [error] 112904#112904: *1 upstream prematurely closed connection while reading response header from upstream, client: REDACTED, server: REDACTED, request: "POST /dns/query HTTP/2.0", upstream: "http://127.0.0.1:65356/dns/query", host: "REDACTED"
`

**Comment by parabolognia** [comment]
Issue is fixed since last commit
