### ISSUE TITLE
)["bytesFrom"] is not a function

### ISSUE THREAD

**Issue by hasankayra04** [TuxInvader/nginx-dns#23]
When i use doh the error below pops up and no response is given to dns request.
[error] 1217#1217: *824912 js exception: TypeError: (intermediate value)["bytesFrom"] is not a function
    at module (/etc/nginx/njs.d/dns/dns.js:28)
    nginx.conf:
    https://paste.hasankayra04.com/paste.php?id=6
    sites-enabled/default:
    https://paste.hasankayra04.com/paste.php?id=7

**Comment by TuxInvader** [comment]
Hi @hasankayra04,

This was due to the main branch being originally built using now removed string functions. It has been updated to use buffers now. Please pull the update and try again.

Thanks

**Comment by hasankayra04** [comment]
Seems to be fixed now.
