### ISSUE TITLE
Chromium based browsers fail to recognize DoH server

### ISSUE THREAD

**Issue by cangurellobello** [TuxInvader/nginx-dns#5]
I tried setting the domain to both chrome and opera but with no avail. With Firefox everything works fine.

**Comment by SScape** [comment]
I am also having issue with chromium based browsers, but somehow Chrome beta version 86 works

**Comment by TuxInvader** [comment]
Hello,

I've just tested this with latest Chrome on Windows (version 86) and it works as expected. 
Which versions of Chrome were failing? 
I enabled secure DNS and set the provider to customised, and the url `https://<fqdn>/dns-query`

Cheers,
Mark

**Comment by SScape** [comment]
For me, it works on Chrome 86 and newer, doesn't work for Chrome 85 in my case. But I guess you can close this issue now since the latest Chrome stable is 86 and everything is working now.
