### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ScottHelme** [TuxInvader/nginx-dns#6]
I'm trying to setup the DoH to DNS proxy and keep getting `502 Bad Gateway` from my Nginx server.

My `/var/log/nginx/dns-access.log` contains entries such as `127.0.0.1 [13/Jan/2021:17:29:23 +0000] TCP ""`.

I've tried with the `8.8.8.8:53` and `1.1.1.1:53` upstreams.

**Comment by jm66** [comment]
hey @ScottHelme How did you solve this? I'm having the same issue in two different hosts.
